# Generated by Django 6.0.2 on 2026-03-22 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_supplier_product_rating_product_sold_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='country',
            field=models.CharField(default='Pakistan', max_length=50),
        ),
        migrations.AddField(
            model_name='supplier',
            name='country_code',
            field=models.CharField(default='pk', help_text='2-letter code e.g. pk, us, de, in', max_length=2),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='location',
            field=models.CharField(help_text='e.g. Pakpattan, Lahore, Berlin', max_length=100),
        ),
    ]
