# Generated by Django 6.0.2 on 2026-03-22 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_reviews_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prev_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
