# Generated by Django 6.0.2 on 2026-03-22 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_prev_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='new_price',
        ),
    ]
