# Generated by Django 6.0.2 on 2026-03-22 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_rename_price_product_new_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prev_price',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=10),
        ),
    ]
